// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrjilctrrntahagerklb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyamlsY3Rycm50YWhhZ2Vya2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODA0MjcsImV4cCI6MjA2ODM1NjQyN30.2vecz3Tg31dk5vnsqSwMh26iLVEKfV8i0i6hHemNNdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});