// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opjisgdxnphwtahzjeig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wamlzZ2R4bnBod3RhaHpqZWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTgzNTUsImV4cCI6MjA2NjkzNDM1NX0.Q-LSAZJ49_slviHxCNaf6Rc1mV57SA5V9SqKJ6ixN8Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});